---
- name: start_docker_service
  become: true
  ansible.builtin.service:
    name: docker
    state: started

- name: reload_docker_service
  become: true
  ansible.builtin.service:
    name: docker
    state: reloaded
