---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present


- name: Download Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker
  register: key_download

- name: Dearmor the GPG key
  become: true
  ansible.builtin.command: "gpg --dearmor /etc/apt/keyrings/docker"
  when: key_download.changed

- name: Add Docker APT repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker.gpg arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
    state: present
    update_cache: true
  notify:
    - start_docker_service

- name: Enble docker service
  ansible.builtin.service:
    name: docker
    enabled: true

- name: Enable ipv6 netwroking for docker
  become: true
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: '0600'
  notify:
    - reload_docker_service

- name: Start portainer agent for mangement
  become: true
  community.docker.docker_container:
    name: portainer-agent
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart_policy: always
    state: started
